version: '3.8'
services:
  database:
    container_name: database
    hostname: postgres
    image: postgres
    volumes:
      - ./data/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres

  api:
    build: ./api
    container_name: api
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - postgres
    links:
      - database
    depends_on:
      - database
    environment:
      DB_HOST: host.docker.internal
      DB_USER: postgres
      DB_PASS: postgres
      DB_PASSWORD: postgres

  client:
    build: client
    command: npm start
    restart: always
    container_name: client_frontend
    ports:
      - "3000:3000"
    volumes:
      - client/src/App
      - /app/node_modules
    stdin_open: true
    environment:
        - CHOKIDAR_USEPOLLING=true
    tty: true

networks:
  postgres:
    driver: bridge